# Generated by Django 4.2.7 on 2026-04-05 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reserved', 'Reserved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('zone_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('zone_type', models.CharField(choices=[('hospital', 'Hospital'), ('heritage', 'Heritage (Dharahara)'), ('shopping', 'Shopping Center'), ('government', 'Government Office'), ('cinema', 'Cinema Hall'), ('regular', 'Regular Parking')], default='regular', max_length=20)),
                ('capacity', models.IntegerField(default=0)),
                ('occupied', models.IntegerField(default=0)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('location_x', models.FloatField(default=0.0)),
                ('location_y', models.FloatField(default=0.0)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['zone_id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('vehicle_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Compact', 'Compact'), ('EV', 'Electric Vehicle'), ('Truck', 'Truck'), ('Motorcycle', 'Motorcycle')], default='Sedan', max_length=20)),
                ('driver_license', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('is_premium_member', models.BooleanField(default=False)),
                ('member_since', models.DateTimeField(auto_now_add=True)),
                ('total_parking_hours', models.FloatField(default=0.0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('mobile_payment', 'Mobile Payment'), ('cash', 'Cash'), ('wallet', 'Wallet')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('receipt_url', models.URLField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='parking_app.parkingsession')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('slot_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('slot_type', models.CharField(choices=[('Regular', 'Regular'), ('Compact', 'Compact'), ('EV', 'EV Charging'), ('Handicap', 'Handicap'), ('Premium', 'Premium')], default='Regular', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('is_reserved', models.BooleanField(default=False)),
                ('sensor_id', models.CharField(max_length=50, unique=True)),
                ('location_x', models.FloatField(default=0.0)),
                ('location_y', models.FloatField(default=0.0)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking_app.parkingzone')),
            ],
            options={
                'ordering': ['slot_number'],
            },
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='parking_app.parkingslot'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='parking_app.userprofile'),
        ),
    ]
