# Generated by Django 4.2.7 on 2026-04-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.CharField(db_index=True, max_length=50, unique=True)),
                ('slot_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('duration_hours', models.FloatField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=20)),
                ('account_id', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
