# Generated by Django 4.2.7 on 2026-04-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0002_pendingreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('mobile_payment', 'Mobile Payment'), ('cash', 'Cash'), ('wallet', 'Wallet'), ('esewa', 'eSewa'), ('khalti', 'Khalti')], max_length=20),
        ),
    ]
