# Generated by Django 4.2.7 on 2026-04-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0004_userwallet_alter_parkingsession_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltypoints',
            name='referred_by',
        ),
        migrations.RemoveField(
            model_name='loyaltypoints',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='session',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='DynamicPricing',
        ),
        migrations.DeleteModel(
            name='LoyaltyPoints',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserReview',
        ),
        migrations.DeleteModel(
            name='UserWallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
