# Generated by Django 4.2.7 on 2026-05-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0005_remove_loyaltypoints_referred_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingzone',
            name='zone_type',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('heritage', 'Heritage (Dharahara)'), ('shopping', 'Shopping Center'), ('government', 'Government Office'), ('cinema', 'Cinema Hall'), ('regular', 'Regular Parking'), ('commercial', 'Commercial Area'), ('airport', 'Airport'), ('park', 'Park'), ('office', 'Office Complex'), ('educational', 'Educational Institution')], default='regular', max_length=20),
        ),
    ]
